"""
Django settings for myfit_utility project.

Generated by 'django-admin startproject' using Django 3.1.2.

For more information on this file, see
https://docs.djangoproject.com/en/3.1/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/3.1/ref/settings/
"""
import os
from pathlib import Path
import environ

env = environ.Env()
# reading .env file
environ.Env.read_env()

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/3.1/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = '#^+pcmd#^@zd(ut_28crr0gli0-_hf996l#q_-vpblch6mg$ji'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = env("DEBUG", default=True)

ALLOWED_HOSTS = env("ALLOWED_HOSTS", default=['0.0.0.0', '127.0.0.1', 'localhost'])
PORT = env("PORT", default=8080)


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'rest_framework',
    'myfitapp',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'myfit_utility.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [os.path.join(BASE_DIR, 'myfitapp/templates')],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'myfit_utility.wsgi.application'


# Database
# https://docs.djangoproject.com/en/3.1/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': BASE_DIR / 'db.sqlite3',
    }
}


# Password validation
# https://docs.djangoproject.com/en/3.1/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/3.1/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_L10N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/3.1/howto/static-files/

STATIC_URL = '/static/'

STATICFILES_DIRS = [
    os.path.join(BASE_DIR, 'myfitapp/static')
]

CHROME_PATH = os.path.join(BASE_DIR, 'myfitapp/assets/chromedriver')
METFLUX_JPEG_PATH = os.path.join(BASE_DIR, 'myfitapp/assets/metflux.jpeg')

EMAIL_REGION_NAME = env("EMAIL_REGION_NAME", default='ap-south-1')
EMAIL_SECRET_KEY = env("EMAIL_SECRET_KEYtest", default='BOLv1EKwdMSRyFuNKJ5UEwFORPu3iAEFrTLSo/Ejqdae')
EMAIL_SECRET_KEY_ID = env("EMAIL_SECRET_KEY_IDtest", default='AKIAVA7PLOTDDVFZNXYV')
FROM_ADDR = env("FROM_ADDR", default='email@myfitprint.com')
EMAIL_SUBJECT = env("EMAIL_SUBJECT", default='MyFitPrint: Your health report is available here')
EMAIL_BODY = env("EMAIL_BODY", default='')

INTERNAL_REPORT_URL = f"http://127.0.0.1:{PORT}/api/report?access_hash="+"{}"

MYSQL_HOST = env("MYSQL_HOST", default='127.0.0.1')
MYSQL_PORT = env("MYSQL_PORT", default=3306)
MYSQL_USER = env("MYSQL_USER", default='root')
MYSQL_PASSWORD = env("MYSQL_PASSWORD", default='root')
MYSQL_DATABASE = env("MYSQL_DATABASE", default='metflux_staging')


